# Advanced Python Demonstration: The Numerical Python Library (Numpy)

In [4]:
import numpy as np

## Creating Arrays

In [5]:
my_list = [1, 2, 3]
x = np.array(my_list)
x

array([1, 2, 3])

In [6]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

In [7]:
# create multidimensional array
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [8]:
m.shape

(2, 3)

In [15]:
n = np.arange(0, 30, 2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [16]:
n = n.reshape(3, 5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [18]:
o = np.linspace(0, 4, 9)
o

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ])

In [20]:
o.resize(3, 3)
o

array([[ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ]])

In [21]:
np.ones((2, 3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [22]:
np.zeros((2, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [24]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [26]:
np.diag((4, 5, 6))

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [27]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [28]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [29]:
p = np.ones([2, 3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [31]:
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [32]:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

## Operations

In [35]:
print(x)
print(y)
print(x + y)

[1 2 3]
[4 5 6]
[5 7 9]


In [36]:
x * y

array([ 4, 10, 18])

In [37]:
x ** 2

array([1, 4, 9], dtype=int32)

In [40]:
x.dot(y)

32

In [41]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [42]:
z.shape

(2, 3)

In [43]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [44]:
z.T.shape

(3, 2)

In [45]:
z.dtype

dtype('int32')

In [46]:
z = z.astype('f')
z.dtype

dtype('float32')

In [48]:
a = np.array([-4, -2, 1, 3, 5])

In [49]:
a.sum()

3

In [50]:
a.min()

-4

In [51]:
a.max()

5

In [52]:
a.mean()

0.59999999999999998

In [53]:
a.std()

3.2619012860600183

In [54]:
a.argmax()

4

In [55]:
a.argmin()

0

## Indexing / Slicing

In [57]:
s = np.arange(13) ** 2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144], dtype=int32)

In [58]:
s[0], s[4], s[0:3]

(0, 16, array([0, 1, 4], dtype=int32))

In [59]:
s[-4:]

array([ 81, 100, 121, 144], dtype=int32)

In [62]:
s[-5::-2]

array([64, 36, 16,  4,  0], dtype=int32)

In [63]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [64]:
r[2, 2]

14

In [65]:
r[3, 3:6]

array([21, 22, 23])

In [66]:
r[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [67]:
r[-1, ::2]

array([30, 32, 34])

In [69]:
r[r > 30]

array([31, 32, 33, 34, 35])

In [71]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [72]:
r2 = r
r2[0:3, 0:2] = 0
r2

array([[ 0,  0,  2,  3,  4,  5],
       [ 0,  0,  8,  9, 10, 11],
       [ 0,  0, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [73]:
r

array([[ 0,  0,  2,  3,  4,  5],
       [ 0,  0,  8,  9, 10, 11],
       [ 0,  0, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [74]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  2,  3,  4,  5],
       [ 0,  0,  8,  9, 10, 11],
       [ 0,  0, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [75]:
r_copy[:] = 10
print(r_copy)
print()
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]

[[ 0  0  2  3  4  5]
 [ 0  0  8  9 10 11]
 [ 0  0 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


## Iterating Over Arrays

In [80]:
test = np.random.randint(0, 10, (4, 3))
test

array([[8, 8, 7],
       [2, 0, 0],
       [2, 6, 4],
       [1, 6, 5]])

In [87]:
for row in test:
    print(row)

[8 8 7]
[2 0 0]
[2 6 4]
[1 6 5]


In [88]:
for i in range(len(test)):
    print(test[i])

[8 8 7]
[2 0 0]
[2 6 4]
[1 6 5]


In [95]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [8 8 7]
row 1 is [2 0 0]
row 2 is [2 6 4]
row 3 is [1 6 5]


In [96]:
test2 = test**2
test2

array([[64, 64, 49],
       [ 4,  0,  0],
       [ 4, 36, 16],
       [ 1, 36, 25]], dtype=int32)

In [97]:
for i, j in zip(test, test2):
    print(i, '+', j, '=', i + j)

[8 8 7] + [64 64 49] = [72 72 56]
[2 0 0] + [4 0 0] = [6 0 0]
[2 6 4] + [ 4 36 16] = [ 6 42 20]
[1 6 5] + [ 1 36 25] = [ 2 42 30]
